version: "3.1"

services:
  iniot:
    image: iniot
    restart: always
    volumes:
      - ../volumes/iniot/data:/data
      - .:/home/iniot
    # network_mode: "host"
    ports: 
      - 8070:8070
