version: "3.1"

services:
  inpyiot:
    image: inpyiot
    restart: always
    volumes:
      - ../volumes/inpyiot/data:/data
      - .:/home/inpyiot
    # network_mode: "host"
    ports: 
      - 8070:8070
